apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostpaths.storage.yourcompany.com
spec:
  group: storage.yourcompany.com
  names:
    kind: HostPath
    listKind: HostPathList
    plural: hostpaths
    singular: hostpath
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
