---
apiVersion: storage.yourcompany.com/v1alpha1
kind: HostPath
metadata:
  name: example-hostpath
spec:
  replicas: 1
  logLevel: 5
  driver:
    repo: quay.io/k8scsi
    imagePullPolicy: Always
  sidecar:
    repo: quay.io/k8scsi
    imagePullPolicy: Always
  storageClass:
    create: true
    default: false
    name: csi-hostpath-sc
    reclaimPolicy: Delete
    allowVolumeExpansion: True
    fstype: ext4

# Other ideas for your plugin...
# mgmt_server_config:
#   protocol: https
#    server: your.server.com:4000
#    username: admin
#    password: <secret>
