---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostpath-csi-operator
subjects:
- kind: ServiceAccount
  name: hostpath-csi-operator
roleRef:
  kind: Role
  name: hostpath-csi-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostpath-csi-driver-binding
subjects:
  - kind: ServiceAccount
    name: hostpath-csi-controller
    # replace with non-default namespace name
    namespace: default
  - kind: ServiceAccount
    name: hostpath-csi-node
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: hostpath-csi-driver-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hospath-csi-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: hostpath-csi-controller
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: hostpath-csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostpath-csi-attacher-binding
subjects:
  - kind: ServiceAccount
    name: hostpath-csi-controller
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: hostpath-csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role
subjects:
  - kind: ServiceAccount
    name: hostpath-csi-controller
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-resizer-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: hostpath-csi-controller
roleRef:
  kind: Role
  name: external-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
