---
- name: Output k8s version
  debug:
    msg: "{{ k8s_server_version.kubernetes.gitVersion }}"

- name: Create StorageClass for HostPath
  when: storage_class.create|bool
  k8s:
    definition: "{{ lookup('template', 'hostpath_storageclass.yaml.j2')|from_yaml }}"
    state: "{{ state }}"

- name: Create Namespace for HostPath
  k8s:
    definition: "{{ lookup('template', 'hostpath_namespace.yaml.j2')|from_yaml }}"
    state: "{{ state }}"

- name: Create CSIDriver for HostPath
  k8s:
    definition: "{{ lookup('template', 'hostpath_csidriver.yaml.j2')|from_yaml }}"
    state: "{{ state }}"

- name: Create StatefulSet for HostPath
  k8s:
    definition: "{{ lookup('template', 'hostpath_statefulset.yaml.j2')|from_yaml }}"
    state: "{{ state }}"

- name: Create DaemonSet for HostPath
  k8s:
    definition: "{{ lookup('template', 'hostpath_daemonset.yaml.j2')|from_yaml }}"
    state: "{{ state }}"
